// LearningAngular/src/app/components/formulario/formulario.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-formulario',
  templateUrl: './formulario.component.html',
  styleUrls: ['./formulario.component.css']
})
export class FormularioComponent implements OnInit {

	public user: any;

  constructor() { 
  	this.user = {
  		nombre: '',
  		apellidos: '',
  		bio: '',
  		genero: ''
  	};
  }

  ngOnInit(): void {
  }

  onSubmit() {
  	alert('Formulario enviado');
  	console.log(this.user);
  }

}

<app-slider [nombre]="'Formulario'" [size]="'small'"></app-slider>

<div class="center">
  <section id='content'>
	<h1 class="subheader">Formulario</h1>
  <div id="datos-al-vuelo" *ngIf="user.nombre">
    <h2 class="subheader"> Datos al vuelo </h2>
    <ul>
      <li>
        {{user.nombre}}
      </li>
      <li>
        {{user.apellidos}}
      </li>
      <li>
        {{user.bio}}
      </li>
      <li>
        {{user.genero}}
      </li>
    </ul>
  </div>
  <!-- #userForm nos permite darle nombre al formulario
  El formulario es de tipo ngForm -->
	{{user.nombre}}
  <form class="mid-form" #userForm="ngForm" (ngSubmit)="onSubmit()" action="">
        <div class="form-group">
          <label for="nombre">Nombre</label>
          <!-- Indico el nombre del formulario de Angular con #nombre -->
          <!-- Con [(ngModel)] digo que modifique el la propiedad nombre de user -->
          <input type="text" name="nombre" #nombre="ngModel" [(ngModel)] = "user.nombre" value="">
        </div>

        <div class="form-group">
          <label for="nombre">Apellidos</label>
          <input type="text" name="apellidos" #apellidos="ngModel" [(ngModel)] = "user.apellidos" value="">
        </div>

        <div class="form-group">
          <label for="nombre">Biografía</label>
          <textarea name="bio" #bio="ngModel" [(ngModel)] = "user.bio" rows="8" cols="80"></textarea>
        </div>
        <div class="form-group radio-buttons">
          <input type="radio" name="genero" value="hombre" [(ngModel)]="user.genero"/> Hombre
          <input type="radio" name="genero" value="mujer" [(ngModel)]="user.genero"/> Mujer
          <input type="radio" name="genero" value="otro" [(ngModel)]="user.genero"/> Otro
        </div>
        <div class="clearfix"></div>
        <input class="btn btn-succes" type="submit" name="enviar" value="Enviar">

      </form>
 </section>
</div>

// LearningReact/learning-react/src/components/Formulario.js
import React, { Component } from 'react';

import Sidebar from './Sidebar';

class Formulario extends Component {

	nombreRef = React.createRef();
	apellidosRef = React.createRef();
	bioRef = React.createRef();
	generoHombreRef = React.createRef();
	generoMujerRef = React.createRef();
	generoOtroRef = React.createRef();

	recibirFormulario = (event) => {
		event.preventDefault(); // Esto es para que no recargue la pagina
		console.log('Formulario enviado');
		console.log(this.nombreRef);
		console.log(this.nombreRef.current.value);
	}

	render() {
		return(
			<div id="formulario">
			    <div className="center">
					<div id="content">
								<h1 className="subheader">Formulario</h1>
					      <form className="mid-form" onSubmit={this.recibirFormulario}>
					        <div className="form-group">
					          <label htmlFor="nombre">Nombre</label>
					          <input type="text" name="nombre" ref={this.nombreRef}/>
					        </div>

					        <div className="form-group">
					          <label htmlFor="nombre">Apellidos</label>
					          <input type="text" name="nombre" ref={this.apellidosRef}/>
					        </div>

					        <div className="form-group">
					          <label htmlFor="nombre">Biografía</label>
					          <textarea name="bio" rows="8" cols="80" ref={this.bioRef}></textarea>
					        </div>
					        <div className="form-group radio-buttons">
					          <input type="radio" name="genero" value="hombre" ref={this.generoHombreRef}/> Hombre
					          <input type="radio" name="genero" value="hombre"  ref={this.generoMujerRef}/> Mujer
					          <input type="radio" name="genero" value="hombre"  ref={this.generoOtroRef}/> Otro
					        </div>
					        <div className="clearfix"></div>
					        <input className="btn btn-succes" type="submit" name="enviar" value="Enviar"/>

					      </form>
					</div>
					<Sidebar
						blog="false"
					/>
				</div>
			</div>
		);
	}
}

export default Formulario;
