// LearningReact/learning-react/src/components/Pelicula.js
import React, { Component } from 'react';

class Pelicula extends Component {
	render() {
		const { title, image } = this.props.pelicula;
		return(
			<article className="article-item" id="article-template">
				<h2>{title}</h2>
	            <div className="image-wrap">
	              <img src={image} alt={title}/>
	            </div>

	            <h2>Articulo de prueba</h2>
	            <span className="date">
	              Hace 5 minutos
	            </span>
	            <a href="#">Leer más</a>
	            <div className="clearfix"></div>
	        </article>
		);
	}
}

export default Pelicula;

// LearningAngular/src/app/components/pelicula/pelicula.component.ts
import { Component, OnInit, Input } from '@angular/core';

import { Pelicula } from '../models/pelicula';

@Component({
  selector: 'app-pelicula',
  templateUrl: './pelicula.component.html',
  styleUrls: ['./pelicula.component.css']
})
export class PeliculaComponent implements OnInit {

	@Input() pelicula: Pelicula;

  constructor() { }

  ngOnInit(): void {
  }

}

<article class="article-item" id="article-template">
	<div class="image-wrap">
	  <img src="{{pelicula.image}}" alt="{{pelicula.image}}">
	</div>

	<h2>{{pelicula.title}}</h2>
	<span class="date">
	  Hace 5 minutos
	</span>

	<!-- Esta es una forma de incluir estilos -->
	<!-- <span class="year" [class.year-red-one]="pelicula.year > 2016"
	                  [class.year-red-two]="pelicula.year < 2016"> -->

	  <!-- Esta es otra -->
	  <span class="year" [ngClass]="{
	                        'year-red-one': pelicula.year > 2016,
	                        'year-red-two': pelicula.year < 2016
	                      }">
	  {{pelicula.year}}
	</span>

	<a href="#">Leer más</a>
	<div class="clearfix"></div>
</article>
